version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  api:
    build:
      context: .
    container_name: api_container
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  mongodb_data: